### ISSUE TITLE
Feature Request: Prusa support

### ISSUE THREAD

**Issue by Mordevolt** [Molodos/ElegooNeptuneThumbnails#11]
Any chance for Prusa slicer support? 
Found similar project, but not for Neptune 3, probably can be used as reference: https://github.com/slawkis/png2mks

**Comment by Molodos** [comment]
Currently I am not planning to release a Prusa Version of the Plugin. Maybe in further distance, there could be a chance, but for now I do not have enough time to do that. I will keep this request in mind, but do not expect any news too soon :D

**Comment by Molodos** [comment]
Good news: Lite version for cura is out, check it out here: https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa
