### ISSUE TITLE
Not showing up under extensions tab

### ISSUE THREAD

**Issue by GSMaxxx** [Molodos/ElegooNeptuneThumbnails#20]
**Question:**
The extension isn't showing up under the extensions tab,

**Additional information:**
I've tried restarting,  it just refuses to show up, any ideas? downloaded from the marketplace

**Comment by Molodos** [comment]
The Marketplace Version is outdated because Ultimaker takes Months to verify an Update (thats ridiculous). Therefore the GUI is only in the GitHub version for now, thry installing it that way :)

**Comment by GSMaxxx** [comment]
i did try that, doesn't seem to work either :'( i dragged the base.curaprofile into cura and restarted

**Comment by GSMaxxx** [comment]
That's totally my bad, i realized the name was different but i always forget the releases tab. Still, i downloaded from the link and dragged it, still didnt work :( i have no idea what im doing wrong now
