### ISSUE TITLE
OrcaSlicer plugin

### ISSUE THREAD

**Issue by martin-badin** [Molodos/ElegooNeptuneThumbnails#27]
**Question:**
Is it possible to create this plugin for OrcaSlicer? I would like to use this plugin but currently, I can't find any way how to generate the picture from OrcaSlicer. Thanks advance

**Comment by Molodos** [comment]
Currently, I do not have the time to do something like this, but feel free to do it if you want to try it. Also after some research, for me, it looks line Orca Slicer doesn't even support plugins.

**Comment by Wal-demar** [comment]
I have same Question:
But Orca have a Post-processing Script section.  I found a script from fifonic [ElegooNeptuneThumbnailPrusaMod for PrusaSlicer/OrcaSlicer](https://github.com/fifonik/ElegooNeptuneThumbnailPrusaMod)
but 1. it doesn't work on my Mac, and 2. it doesn't work on my Artillery Sidewinder X3 Pro.
Is it possible to run the plugin like a script after the G-code generation?
Thanks advance!

**Comment by Molodos** [comment]
There is already a version of this plugin being able to run as a script for PrusaSlicer/Orca, that I made: https://github.com/Molodos/ElegooNeptuneThumbnails-Prusa
Hope that this is what you are looking for :D
