### ISSUE TITLE
解密函数

### ISSUE THREAD

**Issue by Send66** [Molodos/ElegooNeptuneThumbnails#33]
我想问下 这个解密函数是否可以开放出来 我想用到

**Comment by Molodos** [comment]
I am sorry, I do not understand, could you please ask that question in english?

**Comment by DjFingers** [comment]
translation .... "I'd like to ask if this decryption function can be made available and I want to use it"

**Comment by Molodos** [comment]
Yep, also got that, but it makes no sense as there is no decryption or encryption anywhere in this project. I guess as there is not more activity on this issue, I'll close it. Feel free to reopen it if needed.
