### ISSUE TITLE
Image on the printing plane

### ISSUE THREAD

**Issue by simben12** [Molodos/ElegooNeptuneThumbnails#34]
**Question:**
Hi, 
I saw from your readme that you have an image on the print plan, how can I do that too? 
Thanks in advance

**Additional information:**
![cura_drag_plugin](https://github.com/Molodos/ElegooNeptuneThumbnails/assets/72664551/4dd29cfb-9fd4-41c2-899c-ed381902b26e)

**Comment by Molodos** [comment]
That has nothing to do with the plugin. It is because I am using the official Elegoo printer definition in Cura :)

**Comment by simben12** [comment]
Oh okay, thanks anyway. In any case I was very happy with the plugin, it
does its job beautifully and I have to thank you for that

Il mer 10 gen 2024, 19:02 Michael Weichenrieder ***@***.***>
ha scritto:

**Comment by Molodos** [comment]
Thank you, happy to hear that :)
