### ISSUE TITLE
not working for elegoo cura

### ISSUE THREAD

**Issue by Breadmasterpro** [Molodos/ElegooNeptuneThumbnails#36]
**General information:**
 - Printer: elegoo neptune 4 pro
 - Printer Firmeware Version:]
 - Cura Version: 4.8.0
 - Plugin Version: 4.0.0
 - Operating System: Windows 11

**Describe the bug:**
it says it was made for a different version or something like that.

**Comment by Molodos** [comment]
Read the Readme. It says, that my plugin is made fur Cura 5.X
