### ISSUE TITLE
Plugin seems to work with Apple's M-series chip

### ISSUE THREAD

**Issue by moose4lord** [Molodos/ElegooNeptuneThumbnails#40]
**Question:**
In your FAQ there's a blurb about not supporting Macs with M-series chips.
I have an M2 Mac mini with Ultimake Cura v5.6 (the ARM64 version) installed and your plugin seems to work fine.

Just FYI

**Additional information:**
Add additional information (optional)

**Comment by Molodos** [comment]
Thanks for the hint! The FAQ was indeed outdated. Since then, I have added full support for Apple M-Series chips and forgot to also update the FAQ. I just updated it :D
