### ISSUE TITLE
Error whan using script to modify temperature/ wood grain effect

### ISSUE THREAD

**Issue by nonamejuju** [Molodos/ElegooNeptuneThumbnails#9]
Hello !

Having and error "time" when used with a script to add woodgrain effect:
https://github.com/MoonCactus/gcode_postprocessors

Removing the thumbnails package and restarting Cura solve it.
Would be nice to be able to use them both :)

**Comment by Molodos** [comment]
Found and fixed the bug, thanks for reporting :D
